-- 코드를 입력하세요
SELECT t.PRODUCT_CODE, SUM(t.PRICE * o.SALES_AMOUNT) AS SALES
FROM PRODUCT t
    JOIN OFFLINE_SALE o ON (t.PRODUCT_ID = o.PRODUCT_ID)
GROUP BY t.product_id
ORDER BY SALES DESC, t.PRODUCT_CODE
;